name: Deploy to EC2new

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove existing files on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          rm -rf /srv/www/*

    - name: Copy repository to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "./*"  
        target: "/srv/www/"


    # - name: SSH into EC2 and deploy
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USER }}
    #     key: ${{ secrets.EC2_PRIVATE_KEY }}
    #     script: |
    #       cd /srv/www/
    #       docker-compose down  # Đảm bảo dừng và xóa các container cũ nếu chúng tồn tại
    #       docker-compose up --build -d  # Build và chạy các service trong background
