name: Deploy to EC2new

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy repository to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "./*"  
        target: "/target/directory/on/ec2"  

    - name: Deploy and Start Application on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /target/directory/on/ec2
          docker-compose down  # Đảm bảo dừng và xóa các container cũ nếu chúng tồn tại
          docker-compose up --build -d  # Build và chạy các service trong background
